package hibernateoracle;
// Generated 12-ene-2022 11:32:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Dept generated by hbm2java
 */
public class Dept  implements java.io.Serializable {


     private byte deptno;
     private String dname;
     private String loc;
     private Set emps = new HashSet(0);

    public Dept() {
    }

	
    public Dept(byte deptno) {
        this.deptno = deptno;
    }
    public Dept(byte deptno, String dname, String loc, Set emps) {
       this.deptno = deptno;
       this.dname = dname;
       this.loc = loc;
       this.emps = emps;
    }

    public Dept(byte deptno, String dname, String loc) {
        this.deptno = deptno;
        this.dname = dname;
        this.loc = loc;
    }
    
    public byte getDeptno() {
        return this.deptno;
    }
    
    public void setDeptno(byte deptno) {
        this.deptno = deptno;
    }
    public String getDname() {
        return this.dname;
    }
    
    public void setDname(String dname) {
        this.dname = dname;
    }
    public String getLoc() {
        return this.loc;
    }
    
    public void setLoc(String loc) {
        this.loc = loc;
    }
    public Set getEmps() {
        return this.emps;
    }
    
    public void setEmps(Set emps) {
        this.emps = emps;
    }




}


